name: MITRA BENUA MINERAL
favicon: null
layout_spectrum: 0
typography_spectrum: 0.4083493303041905
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#ffaf22'
    - '#ffff00'
    - '#ff8000'
    - '#ff0000'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
